TESTING: checkLib from config.packages.BlasLapack(python/BuildSystem/config/packages/BlasLapack.py:94)                                                                                    *********************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
---------------------------------------------------------------------------------------
Could not find a functional BLAS. Run with --with-blas-lib=<lib> to indicate the library containing BLAS.
 Or --download-f-blas-lapack=1 to have one automatically downloaded and installed

 --with-blas-lib=/home/lithomop_user/fblaslapack

 https://ftp.mcs.anl.gov/pub/petsc/externalpackages/


 RUN curl -L -O "https://ftp.mcs.anl.gov/pub/petsc/externalpackages/f2cblaslapack-3.8.0.q2.tar.gz"; tar -xvf f2cblaslapack-3.8.0.q2.tar.gz;


 autoupdate
 mkdir aux-config
 autoreconf
 automake --add-missing
 autoreconf
 ./configure PYTHONPATH=/usr/local/lib/python2.7/dist-packages
 make
 make install


when trying configure on lithomop, it now seems petsc is the problem: ./configure: line 3715: `CIT_PATH_PETSC(2.3.3)'
petsc

put in the directory /home/lithomop_user/petsc-2.3.3-p16/externalpackages the uncompressed, untared file obtained
need to put mpich in the petsc/externalpackages folder. needs to be : ftp://ftp.mcs.anl.gov/pub/petsc/externalpackages/mpich2-1.0.5p4.tar.gz

curl -L -O https://ftp.mcs.anl.gov/pub/petsc/externalpackages/mpich2-1.0.5p4.tar.gz

looks like you need to configure and install mpi after downloaded and 

need to use -prefix for the directory where to install mpi. I guess we install it where we download it?